import { getTranslations, setRequestLocale } from "next-intl/server";
import { LegalPage, contactEmail, type LegalSection } from "@/components/legal/LegalPage";

function sections(locale: string, email: string | null): { intro: string; sections: LegalSection[] } {
  const contact = email ?? (locale === "fr" ? "(adresse à configurer)" : "(address not configured)");
  if (locale === "fr") {
    return {
      intro:
        "En utilisant Parloir, offert gratuitement par Helpy Media inc., vous acceptez les conditions suivantes.",
      sections: [
        {
          heading: "Le service",
          body: (
            <p>
              Parloir organise des débats entre modèles d&apos;IA que vous choisissez et produit une synthèse.
              Le service est gratuit et fourni tel quel, sans garantie de disponibilité. Nous pouvons le
              modifier, le limiter ou l&apos;interrompre.
            </p>
          ),
        },
        {
          heading: "Votre compte OpenRouter et vos coûts",
          body: (
            <p>
              Les débats utilisent votre propre compte OpenRouter. Les frais des modèles payants vous sont
              facturés directement par OpenRouter; Parloir n&apos;y touche pas. Les modèles gratuits sont
              soumis aux limites d&apos;OpenRouter. Vous pouvez fixer une limite de dépenses sur votre clé dans
              votre tableau de bord OpenRouter.
            </p>
          ),
        },
        {
          heading: "Le contenu généré",
          body: (
            <p>
              Les réponses sont générées par des modèles d&apos;IA et peuvent être inexactes ou incomplètes. Elles
              ne constituent pas un avis professionnel (juridique, financier, médical ou autre). Vérifiez-les
              avant d&apos;agir. Vous conservez vos droits sur vos questions et vos synthèses.
            </p>
          ),
        },
        {
          heading: "Utilisation acceptable",
          body: (
            <p>
              N&apos;utilisez pas Parloir pour enfreindre la loi, nuire à autrui ou contourner les politiques
              d&apos;OpenRouter ou des fournisseurs de modèles. Nous limitons le nombre de débats par compte et
              pouvons suspendre un compte en cas d&apos;abus.
            </p>
          ),
        },
        {
          heading: "Droit applicable et contact",
          body: (
            <p>
              Ces conditions sont régies par les lois du Québec et du Canada. Questions : Helpy Media inc.,{" "}
              {contact}.
            </p>
          ),
        },
      ],
    };
  }
  return {
    intro: "By using Parloir, provided free of charge by Helpy Media Inc., you agree to these terms.",
    sections: [
      {
        heading: "The service",
        body: (
          <p>
            Parloir runs debates between AI models you choose and produces a summary. It is free and provided
            as is, with no availability guarantee. We may change, limit or discontinue it.
          </p>
        ),
      },
      {
        heading: "Your OpenRouter account and costs",
        body: (
          <p>
            Debates run on your own OpenRouter account. Paid model usage is billed to you directly by
            OpenRouter; Parloir never touches it. Free models are subject to OpenRouter&apos;s limits. You can
            set a spending limit on your key in your OpenRouter dashboard.
          </p>
        ),
      },
      {
        heading: "Generated content",
        body: (
          <p>
            Answers are generated by AI models and can be wrong or incomplete. They are not professional
            advice (legal, financial, medical or otherwise). Check them before acting. You keep your rights to
            your questions and summaries.
          </p>
        ),
      },
      {
        heading: "Acceptable use",
        body: (
          <p>
            Don&apos;t use Parloir to break the law, harm others, or get around OpenRouter&apos;s or model
            providers&apos; policies. We cap the number of debates per account and may suspend accounts that
            abuse the service.
          </p>
        ),
      },
      {
        heading: "Governing law and contact",
        body: (
          <p>
            These terms are governed by the laws of Québec and Canada. Questions: Helpy Media Inc., {contact}.
          </p>
        ),
      },
    ],
  };
}

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations("Legal");
  const content = sections(locale, contactEmail());
  return <LegalPage title={t("termsTitle")} updated={t("updated")} {...content} />;
}
